language: r
warnings_are_errors: true
sudo: required
install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages(c("SLOPE", "testthat", "knitr", "rmarkdown", "pander"), repos = "http://cran.rstudio.com")'
