# Site settings
title: grpSLOPE
email: alexej.go@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  Tutorials, examples, and other writeups for the R package grpSLOPE
baseurl: "/grpSLOPE" # the subpath of your site, e.g. /blog/
url: "http://www.alexejgossmann.com/" # the base hostname & protocol for your site
github_username: agisga 

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: /:title/
gems:
  - jemoji # Enable emoji
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
